### ISSUE TITLE
Jasonette's Future

### ISSUE THREAD

**Issue by clsource** [Jasonette/Jasonette#23]
Hello
Maybe some of you noticed that @gliechtenstein, Jasonette's creator is not active since June 9 2018. I personally believe he took some well deserved vacations and will come back some day.

In the mean time I have some ideas to keep Jasonette, Cell.js and ST.js alive. I currently have merge permissions to Jasonette repos but not Cell.js or ST.js repos. 

I believe the best approach to manage and keep the flow is converting Jasonette Cell and ST to a mono repo style project. So one repo would be a "Meta Repo" wich will contain all the codes from jasonette android, ios, cell and st.  Each technology would mantain its own repo but only as a way of executing CI tasks and keep the stars. In other words they will be read only. All the issues and pull requests would be in this meta repo. All the commits would flow downstream to each repo using some mono repo tools or github actions that could be created.

This mono repo style would improve the current situation with many issues and pull requests dispersed across many repos and I currently do not have the mental energy or the permissions required to tackle so many places at once.

Here is an article about the subject 
https://medium.com/@patrickleet/mono-repo-or-multi-repo-why-choose-one-when-you-can-have-both-e9c77bd0c668

As for the domain name it could be renewed as a non owner process. I have a little conversation with namecheap and it can be done, but the problem is the dns. I have not access to the domains or servers that Ethan used. I can only renew the domain but not change the servers related to it. So there are two solutions. One is to renew the domain and hope the servers are still alive or two. Buy a new domain name. Waiting to the domain to expire and then buy it again is a risky move that could be done only if the timing is perfect or you are lucky, maybe using something like Namejet.com would help.

Slack can be keeped around because its free and do not require renewal, but I do not have admin access. For the other tools like jasonbase and the forums I currently do not have any way of keeping them alive if the servers are gone.

The final option is forking and create a new organization and domain name, with a new identity. Keep Jasonette alive but with an organization that I have full admin access. So I would now proceed to do that. And if Ethan comes back some day maybe we could merge the projects again. I currently do not have the same amount of time that Ethan had for Jasonette (He was fulltime Jasonette Cell and ST developer with no compensation for 2 years! ) but I surely have the love for the project needed to keep it going foward and alive. 

When everything is setup I will update this issue 👍 
Hope Ethan is well and come back soon. We really miss you @gliechtenstein .

Love to all ❤️

**Comment by dmoco** [comment]
I noticed and have been trying to track him down for the past week after not getting any response to a direct email. I won't jump to any conclusions except to say I believe the current situation is intentional. @gliechtenstein  , if you're reading this and have truly given up on Jasonette and associated projects then please do a managed handover to someone else so that your much appreciated effort and the time others have invested doesn't go to waste. Nobody is going to hang you for having chosen one path (the correct one IMHO) only to decide that another path is better. However, it would be professional courtesy to provide an explanation and give people the ability make their own choice. Leaving things hanging is the worse possible option.

**Comment by dmoco** [comment]
@clsource could you re-open this issue and leave it for a while so others are aware of the situation?

**Comment by alsanchez-dev** [comment]
@clsource  @dmoco  Thank you for re-opening this issue, I agree with dmoco, it is important to let the issue open for a while so others can give their opinion. It is clear that is important to move forward with Jasonette because @gliechtenstein is not active and would be a waste to abandon this fantastic project and paradigm for mobile applications. However, Jasonette is maintained by the community and I think is important that not only one user should have access to everything but more members of the community should have the permissions as well. As is on the official site, Jasonette is free forever and open source forever and that must keep that way. So we must make sure that all the future contributions new versions etc to continue being free, open and that is possible if the community maintain it and not only a single member. That's my opinion and also I think that from now it should be on operation all the pieces that are possible to maintain at this moment such as GitHub contributions and not just to wait for a member to build a whole new site for Jasonette things must be addressed from now community members continue to build mobile apps and they need support. A new site should exist for and by the community and not only managed by a single member. This allows spending more time maintaining the project than if is only one member of the community. So as much as I agree with clsource I also think that more people must be involved in this turn around for Jasonette and the wellness of the whole community.

**Comment by alsanchez-dev** [comment]
In case @gliechtenstein can read this issue.
Definitely, that sounds great!. Would be good to invite community members, I guess the Slack channel, to collaborate with the creation of the new setup, identity and all the ideas on the road. 
So @dmoco @clsource how could we get this done? So that we can proceed to make it a reality, the community is right now using Jasonette to build awesome apps and they need a more robust Jasonette that gets updated the docs when needed that gets new commits etc. 
Can we have a new GitHub done for this Jasonette setup that we are planning?, I mean on these next days with forked repos from the original, so that we can start to update often the repos with contributions. There are many contributions stuck because nobody approved them yet or the pull request has been closed isn't it?

**Comment by alsanchez-dev** [comment]
Hi, @clsource I hope you are doing well! hows it going with this project? is there anything I might be able to help you with? would be of great news to have ready the GitHub repos for Jasonette :)

**Comment by clsource** [comment]
Ok here is it. But the building and other tasks are not automated.
Anyway this is the repo for now :)
https://github.com/choyke/framework

**Comment by alsanchez-dev** [comment]
@clsource it looks great, well done is taking all the important things! I personally like it!, One question can we use an identity similar to what Ethan started to use for Jasonette? that way would be easier to be identified by the other communities, press, developers etc. just some minimalistic style similar to the cat style that Ethan was using { ˃̵̑ᴥ˂̵̑} can we ask the rest of the community? I know they aren't talking that much ... perhaps with good luck, we can collect some opinions about the identity thinking towards that there are people who have tested Jasonette in the past for tech reviews etc.

**Comment by clsource** [comment]
As for the design and identity things I´m not an specialist in those areas. Maybe using the bird 🐦  emoji https://emojipedia.org/bird/ would do for a Choyke 👍 

As the components inside Choyke you can see they maintained to be jasonette, cell and st. Choyke acts like a wrapper only. they will maintain their identity.

**Comment by clsource** [comment]
It can´t be the same because they are different beasts. Choyke is the full package that includes cell.js st.js and jasonette. Jasonette is only android and ios.

In the commits you can see that I maintained history, all Ethan contributions are there. Nothing was lost 👍

**Comment by clsource** [comment]
ok so I think everyone could be happy with this name
https://github.com/jasonelle/jasonelle

👍

**Comment by alsanchez-dev** [comment]
That's a good one or maybe just Jason? sadly not too many people want to bring ideas, Jason is part of the whole framework you know it, even to start developing an app you have to do the $jason 👍  also makes reference to the mobile app to visualize the apps and so on ...

**Comment by clsource** [comment]
Jason is the app in playstore and appstore. And is a name not available in github. Thanks for your suggestion but I believe Jasonelle is good enough 👍 .

**Comment by alsanchez-dev** [comment]
Yes is a good name 👍  I just wanted to offer some extra suggestions since our community members are not being very active..., lets do it Jasonelle! 😃

**Comment by clsource** [comment]
@cpg  Thanks, I hope @gliechtenstein is ok. Yes for the issues and prs it would be a manual process. For now I´m focused on creating the tools for a monorepo style project and ease fixes and bug hunting.

You are more than welcome to collaborate in Jasonelle 👍

**Comment by cpg** [comment]
What is the motivation for having a "monorepo style project"?

I think having a monorepo (whatever that means exactly) is not really a huge priority. Getting people to be able to build and fix some smaller issues would be a way to get things going one step at a time.

What tools are you talking about for a monorepo?

**Comment by clsource** [comment]
As I said earlier in this thread. The motivation for a monorepo is having a centralized stream of changes. A single place to tackle tasks, bugs and contributions. Eliminating the dispersion that currently is present.

Contributing to such repo is easy. Just make some changes in the right directory. Thats all.

I understand that some people would not be happy with such change in how the code is organized, but I really do not have the mental energy required to maintain several different repos with issues and other related stuff. 

I prefer keep it simple. One repo to store all code.

On a side note I was enabled to reverse engineer the Jason App. Now you can use it and compile it yourself.

https://github.com/jasonelle/jasonelle/tree/master/jasonette/examples/jasonapp

👍

**Comment by alsanchez-dev** [comment]
@clsource thanks that is useful 👍

**Comment by alsanchez-dev** [comment]
@clsource Would be great to reverse web Jasonette to run it in a local port, I have been seen it a bit, it seems to be running on nodeJS

**Comment by clsource** [comment]
One step at at time

**Comment by cpg** [comment]
No disrespect, but  I have concluded that the monorepo is a genuinely bad idea, after

* a barrage of inconsequential emails related to issues I have zero concern with. precisely the kind of thing that is touted as a benefit (a "centralized stream" of changes) is a huge bother
* the realization that CI will not work well with a giant (and I mean giant) repo
* realizing that mixing repos for whole self-enclosed codebases that are disparate (iOS/Android) will make things much harder for people to keep local branches for separate projects
* noticing that it will break stats and contributor profiles
* generally willfully breaking things for some perceived notion of "simplicity" against the benefit of all

So, it's decisively a bad idea IMHO. I commend your whole takeover effort, however I would suggest you reconsider the idea. Having them as separate I think will entice more followers to keep this project alive without risking of burying them in a stream of updates they are not concerned about (incidentally, that is what following a whole organization can be used for!).

**Comment by clsource** [comment]
I will try to address the issues and concerns you have.

1.- The barrage of emails could be easily solved by not subscribing to the main repo. You could subscribe to the repo you are interested in and receive only those notifications when changes are made.
2- Again the CI part will be done per repo. Not the whole thing.
3- Does not make much sense to me. Please elaborate futher of what you mean.
4- I'm not doing commit rebasing. Every commit is kept in history I do not know how this would affect people stats.
5- I think i'm not breaking anything. I truly believe this will benefit all the community since now you can have A single place where you can see the whole picture of the components and documentation. So many more eyes could see the code and improve them.

But i'm just starting. So if it something better came in the future it surely can be done and change it.
What I can do right now is

1- Accept pull requests to individual repos like cell, jasonette and st and merge them to the main repo when all the CI test succed.

This could work I think so long I do not have to address issues and questions scattered everywhere.

**Comment by clsource** [comment]
Maybe this diagram shows better what I have in mind.

![code-organization](https://user-images.githubusercontent.com/292738/48917264-a78d5d80-ee64-11e8-95ed-dfb40c4b2eff.png)

**Comment by clsource** [comment]
I found this tool 
https://github.com/mateodelnorte/meta

So now the main repo can easily fetch all changes from the other repos.
I think this will be something everyone will be happy about.

I get a single place to coordinate and see the code.
And everyone gets an individual repo to contribute only on the parts they like 💯

**Comment by ClOne20** [comment]
Nice move @clsource  and I'm very happy to see this new commitment to keep this genius project alive, even a sad part probably happened to the founder, just a feeling from having spoken with him. It's not the kind of guy who will run after a hit and run. ;)

**Comment by alsanchez-dev** [comment]
Well mono repos are fine, Google and other big companies are using them now days. It could be as simple as, npm i -g meta and meta git commit -m 'commit to my area of interest'. But that is good if it makes it easier on your end :)

**Comment by clsource** [comment]
All the code and newest version is at https://jasonelle.com

https://github.com/jasonelle/jasonelle/
