### ISSUE TITLE
Jasonette Built-in Functions

### ISSUE THREAD

**Issue by clsource** [Jasonette/Jasonette#4]
In order to bring more powerful tools. Jasonette should have build-in functions for modifying certain values. As shown here https://github.com/Jasonette/JASONETTE-iOS/issues/257

The proposed syntax is

```
{% {{value}}, html_decode | trim | uppercase | base64_encode | md5 | sha1 | etc %}

{% <jasonette expression> <comma> <post processing functions chainable by | > %}
```

including some common use single params chainable functions for string manipulation.
works similar to pipe in unix systems.

**Comment by maks** [comment]
I like the idea of being able to more easily use JS functions but I think the syntax is not ideal.
I'm speaking from direct experience, I worked with a PHP based CMS called Squiz Matrix few years ago and it had a similar approach of custom functions in its templating language and it became a nightmare t to use.
I would advocate for a way for use to be able to easily add JS into the scope that template expressions execute in. What I mean by that is basically being able to do use a Node style `require()` of any JS url that is then available for use in template expressions.

eg.
somewhere have the **equivalent** of `var html_decode = require(http://foo.com/htmldecode.js)`
then somewhere else in jasonette file:
```{{ html_decode(value) }}```

**Comment by clsource** [comment]
You have a valid point in the nightmarish way of concatenating function calls.

But I think jasonette should have built in functions available outside template evaluation. So it can be applied to values that are not javascript.

Maybe something like
"value" : "`$fn.html_decode({{ $get.name }})`"

Using the aproach you are refering "Node style" could be used for custom functions that are not the built in 👍

**Comment by maks** [comment]
Yes I agree with that too.
But currently using builtin actions is limited to components that support an action property anyway.
I'm not sure what you mean though by
> it can be applied to values that are not javascript
currently something like ```{{ $get.name }}``` *is* javascript even though its a built-in jasonette function.

I would advocate for removing the restriction of only being able to use js expressions inside templates but that is separate to this proposal which I really like. 
To elaborate a bit more on my proposal: we could refer to JS script urls in the head similar to Html:
```
"head" : {
  "require: {
    "html_decode" : "http://foo.com/htmldecode.js"
  }
```
though I don't know if `require` will confuse people with the `$require` action, so maybe `scripts` is a better choice?

Implementation wise, its just a matter of downloading the urls, caching them locally and then adding them in the JS engine scope, just like we do already for parser js file.

@gliechtenstein I have a vague feeling this could also be used as a mechanism for doing custom extensions, though I need to think that through some more.

At the very least, this opens up the way to easily reuse the **huge** amounts of JS code that are already available as well as easily sharing useful jasonette-specific code libraries that people come up with.

**Comment by clsource** [comment]
What about this

```
"head" : {
   "exports" : {
       "html_decode" : "http://example.com/htmldecode.js", // can be a url or {{ }} expression
       "moment" : "http://momen.js"
  }
}
```

This will load inside a special `$js` variable accesible inside `{{ }}` blocks. Used like `{{$js.moment}}`. Jasonette can have built in functions in a special variable named `$js.fn`. Like the html export. Used like `{{$js.fn.html_decode(<my code>)}}`

**Comment by maks** [comment]
@clsource really like that, just not sure about the naming of `$js.fn` but thats a detail that can be worked out, the concept as a whole sounds very good to me, @gliechtenstein what are your thoughts?

**Comment by clsource** [comment]
I don´t know if the `{{ }}` is ready in the head section.
may be it's better this way

```
"head"  : {
  "templates" : {
    "exports" : {...}
  }
}
```

**Comment by gliechtenstein** [comment]
Thanks @clsource I think it's a great idea. 

I generally agree with the proposal but have a few comments.

1. I think `exports` is a misleading term to use here because normally `exports` is used to export an internal method to the outside world, and in this case we're doing the opposite. Maybe we could use something like `scripts` instead and keep the html analogy going. Or if I'm missing something please let me know. Oh, and also please share if there are any other name suggestions.
2. I see that you're requiring a javascript library and assigning it to a certain variable. But I'm not sure if that can be implemented easily. This assumes that we're using a commonjs pattern (like node.js require)., which is not available to how the **JavascriptCore** or **Webviews** work natively.

What I suggest instead is using a simple importing mechanism all web browsers use--simply load scripts into global context. And instead of trying to use node modules use frontend javascript as much as possible. This would mean we have no control over the variable name, but I don't think it's a huge deal. After all, this is how people have been doing web programming for decades.

The simplest implementation would be something like:

```
"head": {
  "scripts": [ 
    "https://cdnjs.cloudflare.com/ajax/libs/underscore.js/1.8.3/underscore-min.js", 
    "https://cdnjs.cloudflare.com/ajax/libs/crypto-js/3.1.9-1/crypto-js.min.js"
  ]
}
```

Then Jasonette would auto-inject all the declared scripts into the current view's JS execution context under `$root` variable (which we already use to contain all the variables including `$jason`, `$cache`, `$get`)

And then we could simply use them in all templates by referring to each library's exposed variable. For example:

```
"head": {
  "scripts": [ 
    "https://cdnjs.cloudflare.com/ajax/libs/underscore.js/1.8.3/underscore-min.js", 
    "https://cdnjs.cloudflare.com/ajax/libs/crypto-js/3.1.9-1/crypto-js.min.js"
  ],
  "actions": {
    "sha256": {
      "type": "$return.success",
      "options": {
        "result": "{{$root.CryptoJS.SHA256($jason.key)}}"
      }
    },
    "filter": {
      "type": "$return.success",
      "options": {
        "result": "{{$root._.where($jason.items, $jason.condition)}}"
      } 
    },
    "filter_test": {
      "trigger": "filter",
      "options": {
        "items": [
          {name: "coffee", drinkable: true},
          {name: "water", drinkable: true},
          {name: "bread", drinkable: true},
          {name: "sewage", drinkable: false}
        ],
        "condition": {
          "drinkable": true
        }
      },
      "success": {
        "type": "$util.alert",
        "options": {
          "title": "hash",
          "description": "{{$jason.result}}"
        }
      }
    },
    "sha256_test": {
      "trigger": "sha256",
      "options": {
        "key": "hello world"
       },
      "success": {
        "type": "$util.alert",
        "options": {
          "title": "hash",
          "description": "{{$jason.result}}"
        }
      }
    }
  }
}
```

In cases where we really need to use a library that only exists as a node module, we can browserify/webpack it and link to that URL (although I think it's a much better idea to find and use a simpler pure front-end js library instead, as most npm modules are super convoluted with all their dependencies, which normally results in a huge file size, which is not desirable when we need to load the js files over the wire)

What do you think?

**Comment by gliechtenstein** [comment]
BTW one limitation with my suggestion above is that we can only load JS by file and can't use a hardcoded JS code. 

It's not so difficult to implement this if this feature is really needed, we just need to make the markup a bit more complex, like this:

```
"head": {
  "scripts": [ 
    {
      "url": "https://cdnjs.cloudflare.com/ajax/libs/underscore.js/1.8.3/underscore-min.js"
    },
    {
      "text": "var randomcolor = function() { return '#'+Math.floor(Math.random()*16777215).toString(16); }"
    }
  ]
}
```

But whether to implement this from version1 depends on whether there are clear and critical enough benefits for this. Would love to hear thoughts.

**Comment by clsource** [comment]
I vote for the little more complex "scripts". Because it will enable custom functions without http. Also, local files could be possible to include?.

With this approach common functions could be added.

```
 "scripts": [ 
    {
      "url": "jasonette.js"
    },
```

**Comment by maks** [comment]
@gliechtenstein crumbs, thanks for picking that up! yes of course can't use commonjs approach easily with webviews without needing to resort to eval which I want to avoid.

:+1: from me too for your scripts array of objects approach, being able to do inline JS would be useful in some cases.

Can we now label this "spec approved" ?

**Comment by gliechtenstein** [comment]
# Final Spec

Here's the final spec. Let me know if something's unclear or if i left something out.

1. head.scripts is an array of script object
2. each script object is a key/value pair
3. script object can have two key types for now
    1. url: url to fetch the JS from. Supports the following protocols for now:
        - file://
        - http:// or https://
    2. text: inline script text
4. does not use commonjs pattern but works like a regular browser--injects the library into global execution scope
5. The global execution scope can be accessed with `$root`

# Example

1. underscore.js
2. crypto.js
3. inline js to generate a random color

```
"head": {
  "scripts": [ 
    {
      "url": "https://cdnjs.cloudflare.com/ajax/libs/underscore.js/1.8.3/underscore-min.js"
    },
    {
      "text": "var randomcolor = function() { return '#'+Math.floor(Math.random()*16777215).toString(16); }"
    },
    {
      "url": "https://cdnjs.cloudflare.com/ajax/libs/crypto-js/3.1.9-1/crypto-js.min.js"
    }
  ],
  "templates": {
    "body": {
      "style": {
        "background": "{{$root.randomcolor()}}"
      }
    }
  },
  "actions": {
    "sha256": {
      "type": "$return.success",
      "options": {
        "result": "{{$root.CryptoJS.SHA256($jason.key)}}"
      }
    },
    "filter": {
      "type": "$return.success",
      "options": {
        "result": "{{$root._.where($jason.items, $jason.condition)}}"
      } 
    },
    "filter_test": {
      "trigger": "filter",
      "options": {
        "items": [
          {name: "coffee", drinkable: true},
          {name: "water", drinkable: true},
          {name: "bread", drinkable: true},
          {name: "sewage", drinkable: false}
        ],
        "condition": {
          "drinkable": true
        }
      },
      "success": {
        "type": "$util.alert",
        "options": {
          "title": "hash",
          "description": "{{$jason.result}}"
        }
      }
    },
    "sha256_test": {
      "trigger": "sha256",
      "options": {
        "key": "hello world"
       },
      "success": {
        "type": "$util.alert",
        "options": {
          "title": "hash",
          "description": "{{$jason.result}}"
        }
      }
    }
  }
}
```

**Comment by clsource** [comment]
I think the spec covers most use cases

- import script from url
- import script from local file
- use inline script

So I vote to be marked as `spec approved`

**Comment by gliechtenstein** [comment]
I worked on this but soon realized that our original spec may not be a good idea. Here are some of the problems I ran into as soon as I started working on it.

## Problems

1. Conceptually I think the script injection logic should be implemented on a template level, not the JASON markup level, since we're injecting JS libraries into template context. Adding a `$jason.head.scripts` attribute to the schema is JASON level spec change, not template level. The JASON parser shouldn't have to know what's going on inside the template engine.
2. It introduces another level of complexity. We need to make sure the scripts are resolved at view load **before** we go into the `$load` event handler. Also need to make sure this gets resolved **AFTER** mixins resolution. It would be better if we can do this without having to worry about all these timing issues. 
3. Not flexible enough => We could only inject the scripts at page load. If we wanted to dynamically inject JS modules at will and clear them from context at will, that was impossible with the previous approach.

## New solution

I was going to propose another solution but then realized just theorizing about these things before actually trying to implement doesn't work because we don't realize what problems we'll run into until we actually start coding. 

So I came up with a solution AND implemented it. Here's the pull request: https://github.com/Jasonette/JASONETTE-iOS/pull/265

And here's how it works:

instead of introducing a new attribute on `$jason.head`, i turned this into **just another action** called `$script.include`. The options syntax is identical to the previous approach. The only difference is that these are actions.

- `$script.include` injects scripts into the context
- `$script.clear` clears all global variables in the current context

With this,

1. It's more flexible because we can inject and clear the context anytime we want through the actions
2. Since we run these inject/clear logic as actions we don't have to worry about the timing issue.
3. It's just another action, so everything takes place within the template engine. All it does is inject the JS variables into the template context. The JASON parser doesn't need to know about script injection.

## Example

To test out, you can try the [$script](https://github.com/Jasonette/JASONETTE-iOS/tree/%24script) branch, and open the example here https://jasonbase.com/things/38wX

You can test out various example actions I wrote there, including crypto, encoding, underscore.js, etc.

## Conclusion

This is a PR AND a proposal, which means this is not necessarily set in stone so I would appreciate feedback.

If there's a better solution we can incorporate them, and if this looks fine we can just go ahead with this approach if there's nothing wrong with it.

**Comment by clsource** [comment]
I think it's better. 

I think an additional option should be added though.

`"include" : ["_", "crypto", "he", "moment", "jasonette"]`

This will add the url for built in jasonette functions and common utility libs.
Like underscore, crypto, he, moment and other helper methods. So you do not need
to add them manually.

```
"type": "$script.include",
          "options": {
            "include" : ["underscore", "crypto", "he", "moment", "jasonette"],
            "items": [
             ...
            ]
```

Internally this can be an dictionary with the `cdn` urls for such libs. And if present will be merged with the `items` array. This is just for convenience on such common use case libs.

This could be configured inside an xml or plist file. Like this.

![imagen](https://user-images.githubusercontent.com/292738/29790087-cdeebf28-8c0e-11e7-9024-7bfe700a9ccd.png)

**Comment by gliechtenstein** [comment]
@clsource that's an interesting idea but needs a better syntax. The syntax we come up with needs to be coherent in the larger context, which means people should be able to intuitively guess something should be available based on other API usage and it should just work.

One of the ways I've been trying to enforce this is to:

1. Try as hard as possible not to create a new attribute
2. Instead try to look at other APIs and see if there's a way to reuse some attribute names

The less number of keywords to remember the more intuitive it will be for users.

So far I think the `url` and `text` options are good enough because these two lets you do pretty much everything, even though it might be more convenient to use the shorter names sometimes.

The problem with shorter names is that we need to keep a registry of mappings between the names and the URL. This is not scalable as we can see what's happening with NPM and I'm not a fan of this at all.

However I do think it's an interesting problem to think about, so will keep this in mind. Maybe we can revisit this problem in the future.

**Comment by gliechtenstein** [comment]
I have finally resolved this. The branches are merged in to both iOS and Android repos:

- iOS: https://github.com/Jasonette/JASONETTE-iOS/pull/265
- Android: https://github.com/Jasonette/JASONETTE-Android/pull/182

This was a huge operation because it involved not just incorporating the $script action but also overhauling the template engine itself. But I have checked both branches against all existing demo apps and some production apps and they seem to be working fine. 

This is available on `develop` branch now.

If you run into any issues, please let me know. Closing.

**Comment by gliechtenstein** [comment]
https://medium.com/@gliechtenstein/javascript-jasonette-90e72af728fe
